# Generated by Django 5.0.6 on 2024-08-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachement',
            name='image',
            field=models.ImageField(upload_to='post_attachments'),
        ),
    ]
